version: '3'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    deploy:
      mode: global # one per swarm
    environment:
      NODE_ENV: production # deploy in prod settings

  slave:
    build:
      context: .
      dockerfile: Dockerfile.slave
    deploy:
      replicas: 6
    environment:
      NODE_ENV: production
